### ISSUE TITLE
Incompatible API in Headers class

### ISSUE THREAD

**Issue by mendlik** [bitinn/node-fetch#127]
Hi,

I use [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) in my project with [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch). Unfortunately there are some incompatibilities between [Headers API](https://developer.mozilla.org/en-US/docs/Web/API/Headers) and https://github.com/bitinn/node-fetch/blob/master/lib/headers.js.

Missing methods:
- entries
- keys
- values

**Comment by bitinn** [comment]
We don't current support Web Worker features, it's not in the Fetch Spec yet, but a Web Worker feature.

https://fetch.spec.whatwg.org/#headers-class

**Comment by mendlik** [comment]
Ok, thanks

**Comment by zbinlin** [comment]
These methods are not in the fetch spec, but in Web IDL's [Iterable declarations](http://heycam.github.io/webidl/#es-iterable), and iterable is defined in fetch's Headers class.

**Comment by bitinn** [comment]
@zbinlin you are right, I wonder where I find the web worker reference, probably a line from MDN.

Anyway I think `iterable` is not in many Node.js environment yet (require ES6 Symbol and iterator support), can we do this without taking on too much complexity or dependency?

**Comment by TimothyGu** [comment]
@bitinn, the for-of syntax and `@@iterator` are indeed ES2015 features, but `entries()`, `values()`, and `keys()` functions can be implemented using ES5 just fine. To do so, the easy way can just be returning an object with `{next, done}`. If we want higher level of standard compliance we should use a prototype-based approach like [es6-iterator](https://www.npmjs.com/package/es6-iterator).

**Comment by jimmywarting** [comment]
It really sucks that we have to support older Node environment cuz some people never update.

I wanted to contribute first but [wasn't allowed to use es6](https://github.com/bitinn/node-fetch/issues/97). So now I'm only subscribed to this repo to help others with some issues whenever I feel like helping. 

Otherwise I would have done something like this long time ago
```javascript
class Headers extends Map {}
```
Map's comes with many methods Header-class are supposed to have.

**Comment by bitinn** [comment]
I am open to a more spec compliant **node-fetch 2.0**, even if it means breaking a few things, like older Node environment. **1.x branch** is good enough at this point I am quite confident developers can find ways to achieve their goals (sometimes a bit dirty or ugly, but that's software development).

The loudest complains we heard are ES6 features and Isomorphism related, so I do feel we may move onto that path eventually. It will be quite an undertaking to bring in the remaining client-side features, and I will admit I don't have enough free time to tackle this problem at the moment.

*Spec compliant* also means:

- removing our UTF-8 conversion and encoding support (`text()` is UTF only).
- encourage web-stream instead of node-stream.

If you interested in such a thing, give me a shout at #8 or #73 

(Plus if people want a fully ES6-compliant module, I am probably not the right guy to drive it, as I am a bit old-fashioned in that I don't fully subscribe to the *tranpile, not polyfill* belief just yet.)

**Comment by soyuka** [comment]
#174

**Comment by TimothyGu** [comment]
This was fixed in #180.
