### ISSUE TITLE
Headers get wrapped

### ISSUE THREAD

**Issue by rbirkby** [bitinn/node-fetch#13]
https://github.com/bitinn/node-fetch/blob/master/index.js#L83 wraps existing headers in another headers instance. The existing headers get lost. Effectively, this is doing:

```javascript
require('es6-promise').polyfill();
global.Headers = require('../node_modules/node-fetch/lib/headers.js');
var headers = new Headers({Accept: 'application/json'})
console.log(new Headers(headers).raw());
```

Resulting in:

```
{}
```

The spec says that headers passed into the fetch options should implement the Headers interface. The present node-fetch implementation treats it as a hash.

**Comment by bitinn** [comment]
Indeed, I might be able to get this fixed by checking if input `headers` is an instance of `Headers`.

Though let me know why you use `Headers` interface instead of a plain object, existing browser implementation and github fetch polyfill all support using a plain object: https://github.com/github/fetch#post-json

**Comment by bitinn** [comment]
v1.1.1 fixes this issue. though I recommend using plain object for simplicity.

**Comment by rbirkby** [comment]
Thanks - I've updated my code to use a plain object and it works nicely
