### ISSUE TITLE
Posting data malfunction

### ISSUE THREAD

**Issue by AliqueWilliams** [bitinn/node-fetch#145]
I'm simply trying to post json data to an express server. I know the post function in the server works because I've tested it in git bash

Here's the fetch code:
```
   addBug(bug) {
    let bugsModified = this.state.bugs.slice()
    bug.id = this.state.bugs.length + 1
    bugsModified.push(bug)

    fetch('http://localhost:3000/api/bugs', {method: 'POST', body: 'test'})
      .then(res => res.status === 200 && this.setState({bugs: bugsModified}))
  }
```

The {body: bugsModified} doesn't seem to send the server anything. Here's the code from the server:
```
app.use(bodyParser.json())

app.post('/api/bugs', (req, res) => {
  const bug = req.body
  console.log(bug) //returns undefined
  bugs.push(bug)
  res.json(bug)
})

app.listen(3000, () => console.log('connected...'))
```

**Comment by bitinn** [comment]
What is your `bugsModified`? I doubt it's a string/buffer/stream.

There is no JSON type in JS, just string or object. And we definitely don't take arbitrary object (nor do Fetch Spec support that).

ref:
- https://github.com/bitinn/node-fetch/blob/master/index.js#L231-L242
- https://fetch.spec.whatwg.org/#concept-body

(As a side-note, you should reduce your code to minimal test case, in this case you are not getting proper help because you fail to make it readable for developers not familiar with your codebase)

**Comment by AliqueWilliams** [comment]
In the example code, I'm actually just sending a string. 
`body: 'test'}`
It doesn't matter what I send, it doesn't work. I've tried sending all types of data.

**Comment by bitinn** [comment]
> It doesn't matter what I send, it doesn't work. I've tried sending all types of data.

This is your friend, test your code: http://httpbin.org/
