### ISSUE TITLE
WHATWG-URL support

### ISSUE THREAD

**Issue by stevenvachon** [bitinn/node-fetch#175]
[whatwg-url](https://npmjs.com/whatwg-url) is better than core `url`.
```js
fetch( new URL("http://google.com/") )
```

**Comment by bitinn** [comment]
It certainly looks promising. But does it solve the "file:///URL" problem?

Because it can open up to quite a lot of nasty things, so much that Fetch Spec decides to leave it out of the spec. Which is also why we opt to leave it alone in #75 .

For I am quite fine with default `url` parser. Did you run into any problems?

ref: https://fetch.spec.whatwg.org/#basic-fetch

**Comment by stevenvachon** [comment]
I'm not aware of the local file problem. Please tell me.

Aside from that, however, core `url.parse` will still parse such URLs, so I don't see a difference there.

**Comment by TimothyGu** [comment]
The support for this could be pretty easily added. The spec for the [Request class](https://fetch.spec.whatwg.org/#request-class) states that the first argument to `new Request()` must be either another `Request` or a `USVString`; WHATWG's URL class when coerced to a string returns the URL in string format.

**Comment by TimothyGu** [comment]
Fixed in v2 branch.
