### ISSUE TITLE
Incompatible API in url encode

### ISSUE THREAD

**Issue by hardfist** [bitinn/node-fetch#176]
It seems that node-fetch doesn't automatic encode url before request while window.fetch does。
The following code when using node-fetch only url2 gets right result while using window.fetch in chrome url1 and url2 get right result

```
//var fetch = require('node-fetch');
function getWeather(){
    var url1 = 'http://wthrcdn.etouch.cn/weather_mini?city='+'长春';
    var url2 = 'http://wthrcdn.etouch.cn/weather_mini?city='+encodeURI('长春');
    var url3 = 'http://wthrcdn.etouch.cn/weather_mini?city='+encodeURI(encodeURI('长春'));
    fetch(url1).then(x => x.text()).then(x => console.log('url1:',x));
    fetch(url2).then(x => x.text()).then(x => console.log('url2:',x))
    fetch(url3).then(x => x.text()).then(x => console.log('url3:',x))
}
getWeather();
```

**Comment by bitinn** [comment]
Hmmm, I don't think this is an easy change because of the potential breaks. Chrome (or browsers in general) is a lot more aggressive on normalizing the url.

It's always a good idea to run your queries through `querystring.escape`, it should handle the percent-encoding for you.

ref: 
- https://github.com/nodejs/node/issues/2113
- https://nodejs.org/api/querystring.html

**Comment by stevenvachon** [comment]
[whatwg-url](https://npmjs.com/whatwg-url) will solve this.

**Comment by bitinn** [comment]
I am pretty sure this is fixed in v2 alpha.
