### ISSUE TITLE
[npm] take `fetch` name

### ISSUE THREAD

**Issue by aeosynth** [bitinn/node-fetch#2]
the `fetch` npm name has been [offered](https://github.com/github/fetch/issues/9#issuecomment-59704339) by @andris9, and github/fetch is using `whatwg-fetch`.

**Comment by bitinn** [comment]
Ah thx, i saw that, but decided to leave it be, given it's quite easy to find `node-fetch` anyway :)

Though if Andris isn't working on `fetch` anymore, a pull request to clarify module status in readme would be good, so people don't need to figure out if `fetch` follows whatwg.

**Comment by aeosynth** [comment]
it's your decision, but the use of `node` is discouraged:

https://docs.npmjs.com/files/package.json:

> - Don't put "js" or "node" in the name. It's assumed that it's js, since you're writing a package.json file, and you can specify the engine using the "engines" field. (See below.)

with iojs gaining popularity, `node` is slightly anachronistic

**Comment by bitinn** [comment]
hopefully this module will be compatible with iojs without change, if not I will need to look into it in the future.

`node-fetch` is in a special position where whatwg spec isn't stable yet, and it splits between client-side and server-side (since npm is runtime agnostic, but runtime has different strength and weakness), so I feel ok violating npm best practice :)

**Comment by caub** [comment]
it would be much easier to use `fetch` name on npm
