### ISSUE TITLE
How to get an array of header values now that getAll has been removed?

### ISSUE THREAD

**Issue by gajus** [bitinn/node-fetch#251]
> Major: remove headers.getAll(); make get() return all headers delimited by commas (per spec)

Server response (`set-cookie`) might include a comma, e.g.

```
Set-Cookie:              ASP.NET_SessionId=4pxd5fecgvg2vaq1nyetxk5z; domain=foo.com; path=/; HttpOnly
Set-Cookie:              SC_ANALYTICS_GLOBAL_COOKIE=a17765ea49144afdb045dac1294323ca|False; domain=foo.com; expires=Wed, 17 Mar
                         2027 17:12:37 -0000; path=/; HttpOnly
Set-Cookie:              UserSessionId=7c47a144-6a12-4ffc-907a-db8a281cca6a|10002|181845|161471|2017-03-17; domain=foo.com; path=/;
                         HttpOnly
```

How do I get individual `set-cookie` values? Breaking by comma as suggested in the change log note is going to produce malformed results.

**Comment by gajus** [comment]
CC @valeriangalliat (https://github.com/valeriangalliat/fetch-cookie/issues/12)

**Comment by bitinn** [comment]
Interesting, in short, Fetch Spec doesn't seem to be dealing with it very well after deprecating `getAll()`. As browsers never have to expose `set-cookie` headers.

Ref:
- https://github.com/whatwg/fetch/issues/506
- https://github.com/whatwg/fetch/issues/189

So that's cost of following latest spec I guess...

**Comment by TimothyGu** [comment]
Indeed, `Set-Cookie` headers don't follow ordinary HTTP rules, and Node.js has a [special case](https://nodejs.org/api/http.html#http_message_headers) for them.

A current work-around is `.raw()['set-cookie']` though it's not optimal. Alternatively, we could resurrect `getAll()` (probably with a different name to disambiguate against the removed function), which provides special handling for `Set-Cookie` headers; or otherwise behave the same as `headers.get().split(',')`.

**Comment by bitinn** [comment]
I suspect my original implementation of `getAll` wasn't handling multiple `set-cookie` headers properly neither.

But I am not sure we should have a generic API similar to `getAll`, because Fetch Spec is trying VERY HARD to get rid of it. Should we just provide a custom function for accessing `set-cookie` headers by wrapping `.raw()['set-cookie']`? It tastes bad but it should be the only one per Node.js doc you linked.

**Comment by gajus** [comment]
> A current work-around is .raw()['set-cookie'] though it's not optimal.

Will this work even if the original headers where in different cases?, e.g. `Set-Cookie`?

**Comment by gajus** [comment]
To answer my own question: yes.

**Comment by gajus** [comment]
> because Fetch Spec is trying VERY HARD to get rid of it

Source?

**Comment by gajus** [comment]
`.raw()` returns corrupted data:

```
cookies { 'cache-control': [ 'private' ],
  connection: [ 'close' ],
  'content-encoding': [ 'gzip' ],
  'content-length': [ '15889' ],
  'content-type': [ 'text/html; charset=utf-8' ],
  date: [ 'Sat, 18 Mar 2017 13:42:35 GMT' ],
  server: [ 'Microsoft-IIS/8.5' ],
  'set-cookie': [ 'ASP.NET_SessionId=plhpebiilbz5pdclj1ue11s0; domain=foo.com; path=/; HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=6bf292f84dd542c9ab042382ec62d640|False; domain=foo.com; expires=Thu, 18-Mar-2027 13:42:36 GMT; path=/; HttpOnly,UserSessionId=3c0e9eae-b37d-45a6-8711-d25792ea04d6|10002|181845|160482|2017-03-18; domain=foo.com; path=/; HttpOnly' ],
  vary: [ 'Accept-Encoding' ],
  'x-content-type-options': [ 'nosniff' ],
  'x-frame-options': [ 'SAMEORIGIN' ],
  'x-serverid': [ 'con2, CON02' ],
  'x-xss-protection': [ '1; mode=block' ] }
```

**Comment by gajus** [comment]
I cannot see any workaround... `node-fetch` doesn't expose `incomingMessage` and `raw()` is as low level as `Headers` have data.

**Comment by annevk** [comment]
@bitinn FWIW, if we ever were to expose cookies in the API the idea would indeed be to give them some kind of special API that deals with their weirdness.

**Comment by TimothyGu** [comment]
#253 is merged, but we still need to document this somehow, or add a specialized API...

**Comment by bitinn** [comment]
Released as v2 alpha.4, better late than never...

**Comment by FabianTe** [comment]
I am unsure, how to solve this now. I can't figure out how to do this still ...

**Comment by codler** [comment]
Workaround 
`(response.headers as any).raw()["set-cookie"]`

**Comment by patlux** [comment]
@codler You saved my life. Thank you.

Really annoying

**Comment by jasonmcaffee** [comment]
@codler Thank you!  This is a very frustrating issue that I hope is officially resolved soon.

**Comment by bitinn** [comment]
AFAIK, you can’t, due to security concerns. Which is why there isn’t an API  for it yet.

(From my phone)
