### ISSUE TITLE
Headers are sanitized to lower case against Fetch spec

### ISSUE THREAD

**Issue by piotrbazan** [bitinn/node-fetch#260]
I raised similar issue in https://github.com/github/fetch/issues/503.

This should be fixed in this project too.

**Comment by bitinn** [comment]
Looks like the spec changes behavior this year...

https://github.com/whatwg/fetch/pull/476

**Comment by bitinn** [comment]
But wait:

> The change shouldn't affect any JavaScript API behavior. They will still expose header names as lowercase even though the case given by the developer is used on the network.

**Comment by bitinn** [comment]
Looks like the way it's going is to:

- Store header name as-is (no normalization)
- Compare header using case-insensitive search (so comparison works either way)
- But when using accessors to get the headers, it will always returns in lowercase (for compatibility).

https://github.com/whatwg/fetch/issues/304

**Comment by bitinn** [comment]
It was a shame as HTTP2 actually enforce lowercase, just that header normalization are breaking some old servers...

**Comment by cstolli** [comment]
totally agree with this, I read the spec the same way, and I find the implementation forcing the lower-case to be a nuisance when working with inflexible middleware like `prentender.js` or a poorly-behaved server.

**Comment by jimmywarting** [comment]
> It was a shame as HTTP2 actually enforce lowercase header

Couldn't agree more 😞

**Comment by jkantr** [comment]
Hey all... soooo @bitinn I had taken a look into this on Sunday and I agree it seemed pretty simple on the surface, and wasn't too bad getting implementing the header class to behave as per the updated spec. But I couldn't get my TDD~ish tests to pass.. and then I realized headers were still being lower-cased over the wire:

https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L519,L525

So basically we could:
1. Monkey patch `http`'s `http.OutgoingMessage.prototype.setHeader` - this seems like not a great idea, because we can't even "properly" do it by using a decorator or before/after pattern, since the functionality we need to skip is right in the middle of the function and I can't think of a good way to do it other than just re-implementing all of `setHeader` and `validateHeader`
2. Ditch `http` and drop down to `net` - this seems like an even worse idea because recreating the wheel
3. Try to get some movement upstream

The applicable open issue is: nodejs/node#3591, and it's been sort of dead. I have started crafting up a response but I haven't decided whether to post there or open a new issue that hasn't been derailed 20 times over 45 messages.

Looking for some input to how you'd like to move forward.. or maybe there's a solution I haven't come up with, thanks :)

**Comment by bitinn** [comment]
Ah man, I was hoping it wasn't something in the internal of `http`, in this case I say we put this issue on hold. Agree? @TimothyGu

**Comment by TimothyGu** [comment]
+1 from me.

**Comment by bitinn** [comment]
But thx @jkantr for digging into this issue!

**Comment by abritinthebay** [comment]
So - fun fact - I'm running into an issue where the header's name.toLowerCase fails because the name is undefined. It tanks `headers.get`. Is this something that would come under this ticket?

**Comment by TimothyGu** [comment]
I'll close out this issue. For the Node.js issue, there isn't really anything actionable from our side. https://github.com/bitinn/node-fetch/commit/1592ca1148e657110fd6f64dc8b29a576cd1da1c should help nevertheless.

**Comment by miro-balaz** [comment]
Information in this thread about Node.js http lowercaing headerse are not longer accurate, i tried it just now and was able to send headers with uppercase.
