### ISSUE TITLE
Make dependency on encoding optional

### ISSUE THREAD

**Issue by bitinn** [bitinn/node-fetch#273]
`node-fetch` has 1 dependency that's [encoding](https://github.com/andris9/encoding), which is really legacy dependency from 1.x era (see [upgrade guide](https://github.com/bitinn/node-fetch/blob/master/UPGRADE-GUIDE.md#text-no-longer-tries-to-detect-encoding)).

My problem with `encoding` is it depends on [iconv-lite](https://github.com/ashtuchkin/iconv-lite), which is kinda huge in size because of what it needs to do.

So given many aren't using such features, I would consider dropping this hard dependency and throw errors when calling `textConverted` without `encoding` installed.

**Comment by fzaninotto** [comment]
I concur: `iconv-lite` adds 130kB to my bundle size. That's really too much for something that's not really necessary.

**Comment by TimothyGu** [comment]
+1.

**Comment by jimmywarting** [comment]
Please don't `+1` any github issue it's annoying to get useless email notifications
We have reaction for that...

**Comment by jkantr** [comment]
Do we have a preferred method to handle a conditional require? It seems like the options are:

1. Mix `import` and `require` syntax. It will still be compatible with the babel transforms we're doing now and we'll be able to do a sync try/catch for the `encoding` package. The downside being.. we're mixing module loader syntax.. however this might end up being a good thing in the future depending on how node decides to implement es modules.
2. Use a babel plugin like `babel-plugin-dynamic-import-node` to use dynamic import() syntax. The downside being that it's still only proposed syntax.. but that seems less bad when you compare it to the fact that the whole loader spec really isn't in an agreed upon state anyway.. and since we're already using `import`..

Personally I'd rather just try/catch require but given that the project is already transpiling for `import` i assume we have some fans of es modules here :)

**Comment by TimothyGu** [comment]
Just go with 1. We can change it later.
