### ISSUE TITLE
Resolve promis later

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#278]
Hi
First of all, this is not an issue or suggestion

It's something I came up with that I maybe think is useful to you who have a long promise chain.
I haven't used it myself for something yet, just wanted to learn about [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

It started with this SO [answer](http://stackoverflow.com/a/44048287/1008999) to: [test for existence of nested object key](http://stackoverflow.com/questions/2631001/javascript-test-for-existence-of-nested-object-key/44048287#44048287)
I wanted to came up with a way to use Proxy to return the result without getting a error
So i came up with another way to make it asynchronous in somewhat "magical" way.

The "something i came up with":
```js
resolve(window) // this will chain a noop function until you call then() 
  .fetch('https://httpbin.org/get?items=4&items=2') // promise 
  .json() // promise 
  .args
  .items
  .map(n => ~~n * 4)
  .then(console.log, console.warn)
```

I'm just wondering if you think it is useful... I publish it at npm: [lazy-resolver](https://npmjs.com/package/lazy-resolver)

**Comment by TimothyGu** [comment]
This, too, is just an opinion from my programming experience. I'm generally for writing [declarative JavaScript](http://benediktmeurer.de/2017/04/03/v8-behind-the-scenes-march-edition/) that is clear, semantic, and hopefully immediately optimizable. This means that I would sometimes sacrifice code cool-looking-ness for a lower barrier of introduction. In other words, I would try to make my code understandable for anyone who knows the Promise and Fetch API, from another project, a textbook, or the spec.

Proxies are unfortunately just one of those things that's pretty much impossible to optimize – especially when one is creating another one of them when getting every property : ) Because it allows changing some of the fundamental internal operations of objects, it's also difficult to predict the behavior of it. In this case, if I didn't know how lazy-resolver works I would be very confused by that piece of code.

This is, again, just my opinion. Different people may have different standards of balance between readability and performance. I obviously think mine is the best (otherwise I wouldn't hold it as my belief), but I understand if other people disagree 👍 :rofl:

**Comment by jimmywarting** [comment]
You are absolutely right. 

This isn't either something you could use in IE either so it would only work for node or updated browsers so there is that...

Even if this isn't something people would use, I think this is an good example what you can use it for and also learn how Proxies works. Must say i haven't found many use cases for proxies yet
But i bet that someone who has a lot of promise chains would think this *lazy-resolver* is useful (fetch came to my mind since it has 2 that must be called - hence why i posted it here)

If you only have a few promies or a not so long promise chain it wouldn't serve a big purpose
Still it can be useful as a replacer to `_.get(obj, path)` if you want to check some deep nested object for it existence

**Comment by TimothyGu** [comment]
As stated by OP, this is not actually an issue, and the discussion has ended some time ago.
