### ISSUE TITLE
Introduce linting to the project

### ISSUE THREAD

**Issue by jkantr** [bitinn/node-fetch#303]
@bitinn, @TimothyGu 

Mostly in an effort to stop myself from committing things missing semi's (I work on a *lot* of no semi projects, heh) I think it might be advantageous to set up linting.

There are already a bunch of different styles being used throughout the code but this is mostly auto-fixable using modern tooling. My suggestion:

- add `eslint` dev dep
- add `eslint-config-airbnb-base` preset dev dep
- add .eslintrc for custom rule negotiation
- add npm script to run linting

This would configure linting to the Airbnb style guide, which is very common (especially among front end packages), and can be read here: https://github.com/airbnb/javascript

Advantages:

- Airbnb style rules have very specific reasonings to back them that are based around clarity and bug avoidance
- Most of the style guidelines already fit well into the current project
- We can easily turn off the rules that we don't need and can re-implement them one at a time til compliance.
- Easier for new contributors to adopt a common style (with even simple things like tabs vs spaces, etc)
- Increases general perceived code quality with more consistency

After we have all rules implemented/agreed on over some time, we could then also:

- have the linting npm script autofix
- implement a git hook or CI step and reject on unlintable styles.

Thoughts?

**Comment by TimothyGu** [comment]
Sounds fine to me. I've used Airbnb before with good experiences as well, though I wouldn't mind [xo](https://www.npmjs.com/package/xo) either.

**Comment by bitinn** [comment]
I am kinda against it, and my main reasoning:

- There are a lot good things we can do before we debate on how to `eslint` styles.
- We might end up turning off rules because sometimes the best practice isn't what we want.

But I do agree *eventually* `eslint` would be a good tool for improving on our codebase.

**Comment by jimmywarting** [comment]
I have always hated it, never dose what I want.
I only get frustrated when i use new syntax that isn't well supported

My principle is only:
 * Code it so it looks consistent with the rest of the code
 * Have somewhere in the back of you head some guidelines, eg like the [jsStandard rules](https://standardjs.com/#the-rules)
   - Dosen't have to be those or everything they rule out
 * And what bitinn said about "turning off rules"

Otherwise you add more complexity, dependencies, compile time, researching "what is wrong with my code, how to make linters happy" and sending new bug reports to something that is wrong or not supported like when the new async/await came for example

But i must admit, Linters is a good tool for the quality of your code. but you must put some more effort into it. But to me it's not worth it

**Comment by jkantr** [comment]
Ok, everyone seems to be split on this :) Putting it on hold for now and can revisit in the future

**Comment by SimenB** [comment]
Can stick prettier in there instead of full eslint? Pretty easy win in my eyes

**Comment by TimothyGu** [comment]
@SimenB IMO it's more the [other stuff](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint) that's useful, like `let`/`const` usage, `var` scoping etc. Code formatting is always the easy part.

**Comment by Richienb** [comment]
Linting has now been added as part of 3.x
