### ISSUE TITLE
Remove dependency of is-stream

### ISSUE THREAD

**Issue by programmer5000-com** [bitinn/node-fetch#304]
Given that the actual code of is-stream **[is 30 lines](https://github.com/sindresorhus/is-stream/blob/master/index.js)**, I think it's OK to just add this to your code:

```javascript
//https://github.com/sindresorhus/is-stream
const isStream = stream => stream !== null && typeof stream === 'object' && typeof stream.pipe === 'function';

isStream.writable = stream => isStream(stream) && stream.writable !== false && typeof stream._write === 'function' && typeof stream._writableState === 'object';

isStream.readable = stream => isStream(stream) && stream.readable !== false && typeof stream._read === 'function' && typeof stream._readableState === 'object';

isStream.duplex = stream => isStream.writable(stream) && isStream.readable(stream);

isStream.transform = stream => isStream.duplex(stream) && typeof stream._transform === 'function' && typeof stream._transformState === 'object';
```

Given that there are 4 million downloads of `node-fetch` last month, it would probably be a good idea to avoid another [left-pad incedent](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/).

**Comment by jkantr** [comment]
- npm makes it viable to use small, single-purpose modules for solving problems, and because of their limited scope, they are very unlikely to ever be deprecated or replaced
- npm has adjusted their unpublishing policies to mitigate the risk of a similar issue in the future
- through shrinkwrap/lockfiles, the mutation risk reduces even more
- reference https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328 , which is a comment written about 100 times better than that infamously poor Haney article

**Comment by bitinn** [comment]
Besides the modular argument:

- If you want a no dependency module, well we have v2.x, we plan to drop the last hard dependency `encoding` as well.
- I won't be making additional changes to v1.x unless it's bugfix related.
