### ISSUE TITLE
POST request doesn't seem to throw errors

### ISSUE THREAD

**Issue by pjg** [bitinn/node-fetch#305]
```javascript
const fetch = require('node-fetch');

const requestOpts = {
  method: 'POST'
}

fetch('https://gists.github.com/abcd', requestOpts)
  .then(response => {
    console.log(`ok? ${ response.ok }`);
    console.log(`${ response.status } ${ response.statusText }`);
  })
  .catch(error => { console.log(error); })
```

The above will output:

```
ok? false
405 Method Not Allowed
```

As you might notice, it was handled in the `then` block as a regular, successful request (which it wasn't). If it was a regular `GET` request, it would throw an error on anything other than 2xx. For `POST` requests it doesn't throw errors at all.

Am I missing something?

**Comment by pjg** [comment]
Ah, nvm. For `GET` 404/500, etc requests it won't throw as well. Not what I expected.

**Comment by jkantr** [comment]
This is as per the fetch specification. It does confuse some people because they are used to other client libraries like ajax throwing on certain types of response codes... but if you consider it, it does make a lot of sense. Fetch basically throws an error when there is an error in the request. Something syntax wise, something on the wire (connection reset), etc. Once the server you're connecting to receives the request and finishes the response, the transaction has completely successfully :)

A common pattern you might use is something like:

```javascript
const checkResponse = (response) => {
    if (response.status >= 200 && response.status < 300) {
        return response;
    }
    throw new Error(response.statusText);
})

fetch(url)
    .then(checkResponse)
    .then((res) => {
        // ...
     })
     .catch(error => { console.log(error); })
```

This way you can still throw an error on a response outside of your expected response range. Also you should probably patch some sort of prop onto the error object here or use a predicate to denote a bad response code vs a FetchError.

I'll check out the docs tho and see if there's a way we can make this clearer.

**Comment by pjg** [comment]
Thanks for the explanation. Yes, it does make sense. Just not something I expected. And thank you for the exemplary code! I have already started coding something along those lines, but your handling of incorrect response is way better (I can only suggesting using `response.ok` instead of checking for response codes directly).

**Comment by bitinn** [comment]
BTW, an even shorter pattern for this:

```
if (response.status >= 200 && response.status < 300) {
  // ...
}

if (response.ok) {
  // same
}
```
