### ISSUE TITLE
converting import's to require

### ISSUE THREAD

**Issue by caub** [bitinn/node-fetch#310]
Is there an important reason for using import/export instead of require/exports?  
It's a pain to test and develop with babel. With a recent node there are just the import/export missing, which are quite equivalent anyway, is it ok to replace them?

**Comment by TimothyGu** [comment]
We use [Rollup](https://rollupjs.org/) to create a bundle when publishing, which basically requires import/export. Personally I don't think it's too terrible to run `npm run build` or `yarn build` before launching `node` to test a change, and unless there's some trick I don't know about you have to restart the `node` REPL after changing something anyway because of `require()` caching.

**Comment by caub** [comment]
Ah, ok thanks, I could try to configure it on sublime text for example
