### ISSUE TITLE
[2.0.0-alpha.7] https import missing in es modules build

### ISSUE THREAD

**Issue by gpoitch** [bitinn/node-fetch#318]
The `https` import seems to be stripped out of the es modules build:
https://unpkg.com/node-fetch@2.0.0-alpha.7/lib/index.es.js

So any https url requests are throwing `ReferenceError: https is not defined`

**Comment by bitinn** [comment]
@TimothyGu you might want to take a look at this, seems like after #243 I no longer see `https` in the `index.es.js` build. Am I missing some installation steps before `npm publish`?

**Comment by TimothyGu** [comment]
Well, I have absolutely no idea why it's failing. But it doesn't matter anymore, since I'm tired of pretending Node.js core modules were designed to be loaded with `import`, so I just changed all the `import`s to `require()`s for core modules.

**Comment by bitinn** [comment]
released as alpha.8, thx all involved!

**Comment by tinovyatkin** [comment]
Why not just switch to native ES6 with node 6 requirement? Node 8 will be LTS in few days, but mixed `import`/`require` syntax looks horrible...

**Comment by bitinn** [comment]
@tinovyatkin because `import` is what causes this issue, and no one can figure out why rollup/babel decides to strip a particular native module import (in this case `https`)

So yes, we decide having thing work is way better than having thing look nice but fails for unknown reasons.

**Comment by jkantr** [comment]
Not using `import` at all is probably a more sane choice ultimately. ES Modules really aren't a thing and are generally just transpiled out by babel/typescript/fooTranspiler. I guess webpack and rollup have their own magic but since the implementation spec is still wayyyyyyy up in the air.. and when es modules finally hit node they will be via `.mjs` file extension.. and since this is a node.js package... just trying to get to the logical conclusion...

**Comment by TimothyGu** [comment]
@jkantr Yes I know the semantics difference between Babel and the spec and I know how the ESM loader in Node.js will work (in fact I helped implement a part of it). The decision to use Rollup here is purely so that when we publish the module we only publish one file, which helps for memory usage etc., while keeping our internal source tree intact. Browserify does this too, but it adds a bunch of function wrappers that are really unneeded.
