### ISSUE TITLE
Unable to resolve module ... after installation

### ISSUE THREAD

**Issue by Tom29** [bitinn/node-fetch#321]
I installed version 1 and got this error.

![simulator screen shot jul 29 2017 12 12 29 am](https://user-images.githubusercontent.com/5781080/28728372-a111c09c-73f2-11e7-8291-33840fe32b7d.png)

**Comment by bitinn** [comment]
This is not the issue tracker your issue.

**Comment by Tom29** [comment]
@bitinn I installed it, do as tutorial then this error occurred.
I report an error then you ask me to ask for the solution on StackOverflow ?!
What's purpose of `Issues tab`?
You should disable the `issues` tab or remove your repo and use it for yourself only.

**Comment by jkantr** [comment]
@Tom29  This issue has nothing to do with `node-fetch` is what he's saying. We also have no idea what we are looking at (you just pasted an image?). It would *appear* however that you don't have the `url` module available (which i believe is node > 7?), you can use the npm package `whatwg-url` as an alternative

**Comment by Tom29** [comment]
@jkantr He said nothing but telling me "this is not an issue tracker"
I installed the app, write down one line of code to test:
`import fetch from 'node-fetch'` then got this error.

What am i supposed to do? Write an A4 page of text to describe the error?

You really couldn't read the img / text and see the `node_modules/**node-fetch/index.js**`
Its not related this repo? If i have this error, it means many can.

I've read whole installation instruction, searched all issues and no-one mentioned it thats why i created this.

**Comment by TimothyGu** [comment]
The url module has been in Node.js from the very beginning, only url.URL is v7.x+.

@Tom29 No need to get cranky here. If you look at `node_modules/react_native/node_modules/node_fetch/index.js` you would see that node_fetch is getting included by react_native, which 1) may not be the react-native you are looking for and 2) means that you are not directly including node-fetch, thus would probably be luckier file this issue elsewhere.

If you strongly believe this is a bug with node-fetch, then you need to provide us with enough steps to reproduce – yes that does mean an A4 page of text, or even more if necessary. If and only if you do that can we provide help to your situation.

**Comment by bitinn** [comment]
@Tom29

I was a bit harsh when responding your post, for that I apologise.

- You say you installed _the app_, not knowing `node-fetch` is written for Node.js but not _the app_. We have no knowledge of _the app_. If you want to report an issue, **you have to reproduce the issue in Node.js**, otherwise you are expecting us to learn _the app_, for you, for free.

- From the errors it's quite obvious to a Node.js developer the problem is coming from React Native, again, a package that relies on Node.js; if you have little knowledge of it, perhaps talking to the author of _the app_ makes more sense.

- What you should do, tell the author `import fetch from 'node-fetch'` results in your error. Give he/she the full details. And see if he/she has a solution. Again, `node-fetch` knows little about _the app_. It's like saying _my process crashed so let's submit a bug report to linux kernel bug tracker_.

**Comment by araujobarret** [comment]
@Tom29 ,

The React Native already have an integration with node-fetch, you do not need to import anything.

You can check this [link](https://facebook.github.io/react-native/docs/network.html) to see if it helps you out.
