### ISSUE TITLE
Send readable stream as part of multipart form data

### ISSUE THREAD

**Issue by YaManicKill** [bitinn/node-fetch#347]
Hi there,

I'm trying to use fetch to send a file in a multipart form data. I'm pretty sure this is how it should work. But when I do this:

```
	var form = new FormData();
	form.append('apikey ', 'removed');
	form.append('file', fs.createReadStream(path.join(HOME, 'Screenshots', name)));
	fetch('https://domain/api/upload', { method: 'POST', body: form });
```

I get this:

```
Error: body used already for: https://domain/api/upload
```

It seems like if you want to send a readable stream, you have to only send it, not send it as part of a FormData. Am I missing something here?

**Comment by bitinn** [comment]
The error you got means the req.body is somehow already consumed. Since it's a stream, it comes with all the stream limit.

I am not sure how exactly you send the request. But look at this similar test, you probably are doing something wrong in between:

https://github.com/bitinn/node-fetch/blob/master/test/test.js#L815-L833

Also not sure which version you are on, but we tested node-fetch 1.x/2.x with form-data 1.x / 2.x

**Comment by YaManicKill** [comment]
Ah yes, sorry, I was calling res.json() twice. Apologies.
