### ISSUE TITLE
Should node-fetch coerce to string if possible?

### ISSUE THREAD

**Issue by kenmorechalfant** [bitinn/node-fetch#359]
When I have a URL such as:

```
const { URL } = require('url');
const fbUrl = new URL('https://graph.facebook.com/');
console.log(fbUrl.toString()); // 'https://graph.facebook.com/'
```

If I pass this object to `node-fetch` it gives the error `TypeError: Parameter "url" must be a string, not object`.

However, in Chrome and Firefox (can't test any others right now), using their native fetch implementations, if you pass fetch an object that has a toString() function, they will use that as the url.

Is this mentioned in the spec anywhere? And/or should 'node-fetch' match what browsers do?

**Comment by TimothyGu** [comment]
Yeah, this is part of the spec. See [`RequestInfo`](https://fetch.spec.whatwg.org/#requestinfo) typedef, which is the type of the first argument of `fetch()`. The problem is we want to simultaneously support the Node.js `url.parse` "URL" that does not implement `toString()`, and WHATWG URL objects that do, and it is difficult to distinguish between those two. So what we currently do is by looking at the `href` property of both, which is a nice compromise that supports most cases.
