### ISSUE TITLE
POST request with uppercase sometimes calls GET

### ISSUE THREAD

**Issue by kjschulz** [bitinn/node-fetch#369]
Documentation says to use uppercase method constants but I'm experience intermittent issues where in some cases uppercase method usage will actually call `GET` instead of `POST` when checking the server logs:
```javascript
var fetch = require('node-fetch');
var opts = {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    key: 'value-here'
  })
};
fetch('SOME-URI-HERE', opts)
  .then(function(request) {
    return request.json();
  })
  .then(function(response) {
    json.res(response);
  });
```

`^^^^^^^^` The same code above with a subtle change to the method constant where `post` is used instead of `POST` causes everything to behave as expected.  This is problematic as it's undocumented, seemingly random, and took some time to track down since we use a micro service architecture and this was a service called by another service downstream.  I should mention also that it was only a problem in production and not locally...but I'm not sure that has any bearing on the issue as even if it were about different versions of Node or something it should just work the same with uppercase as lowercase.

I'm using version `1.6.0` but I don't see anything in the changelog that mentions a fix in newer versions. 

Please advise.

**Comment by bitinn** [comment]
First of all, no we don’t change POST to GET, there are only 1 case where POST will be follow by a GET, that’s when server redirects a POST request. We do it per Fetch Spec.

Second, there are no change log on this because there are no issue related to random request method change.

Third, the fact you can’t reproduce locally means you are missing something, or maybe the server log is misleading. Investigate that instead of asking us to figure it out for you.

Lastly, update your node-fetch to latest. There are no reason why you should troubleshoot an outdated version. It probably won’t fix your issue but you know it’s not node-fetch’s issue.

Or if you still believe this is the case, reproduce it using minimal code.

That’s as much free advice as I got.

(From my phone)

**Comment by Elliot128** [comment]
@kjschulz ran into the same issue as you. Changing to lowercase works. I don't think we are doing any redirects in our case.

**Comment by stewartlord** [comment]
I am seeing a similar problem here. Switching the method to 'post' (lowercase) resolved the problem for me as well.
