### ISSUE TITLE
Expose Blob

### ISSUE THREAD

**Issue by modulesio** [bitinn/node-fetch#392]
Does it make sense to expose `Blob` [here](https://github.com/bitinn/node-fetch/blob/v2.0.0-alpha.9/src/index.js#L200)?

Since `Response` is exported, and `Response` supports `Blob`, not exporting it hinders usability of that.

It seems if someone wanted to they could grab the `Blob` `.constructor` anyway, so hiding it doesn't add any security/encapsulation.

**Comment by TimothyGu** [comment]
Right now I don't want to expose the `Blob` class, as it's very possible that Node.js will add a `Blob`/`File` class as well that can be shared for all modules. I'm only providing the `res.blob()` API to allow for direct usage of the `Blob`'s properties, and to use this `Blob` as the body of another fetch.

**Comment by modulesio** [comment]
Makes sense. If node added Blob I suppose node-fetch would just use that as a drop in.

It's just weird right now since Response effectively does not support constructed Blobs without hacks.

I'll fork for now, but we'll probably end up in the same place. Thanks!

**Comment by mattlubner** [comment]
Not exporting Blob from node-fetch poses a slight problem with testing assertions. We can't do `myBlob instanceof Blob` because we can't access the `Blob` constructor used to create a particular blob.

Could we reconsider exporting the Blob implementation from node-fetch? It would be fine if done in a clunky way, like `export TESTONLY_Blob`, to emphasize that it should not be relied on in production code.

I'm doing `expect(qrBlob.constructor.name).toBe('Blob');` for now, but it's not as strong of an assertion, so not ideal.

**Comment by jimmywarting** [comment]
> @Gozala
>
>I'm using node-fetch with https://github.com/RangerMauve/webrun/ and running into problem because `Blob` class can't be referenced nor there is a way to extract bytes from it. Please consider exposing so it could be used.

**Comment by Gozala** [comment]
@jimmywarting if you use web compatibly libraries they assume `Blob` is available and often attempt to instantiate it, problem with that is they either fail or instantiate different `Blob` implementation which than can't be used with this library because it's unable to recognize it. Essentially this means this library is unable to interop with any other library that uses `Blob`s because implementations are different & incompatible.

Exposing `Blob` would make it possible to use it across libraries and avoid the interop issues.

**Comment by Gozala** [comment]
@modulesio Did you end up forking ? And if so is it maintained / published on npm ?

**Comment by jimmywarting** [comment]
A solution for now:

If you want to build a node based FileReader you can always extract the content from the the blob with the fetch api itself

```js
var fetch = require("node-fetch")
var { Response } = fetch

fetch('https://httpbin.org/get').then(res => res.blob()).then(blob => {
  new Response(blob).text().then(console.log)
})
```
working example: https://runkit.com/jimmywarting/5ca7edaf0caebe00123912ef


so kinda something like this:
```js
FileReader.prototype.readAsText = function (blob) {
  new Response(blob).text().then(text => {
    this.result = text
    // dispatch evt
  })
}
```

Or don't use blob, use arrayBuffer instead

**Comment by jimmywarting** [comment]
FIY: if this gets added https://github.com/w3c/FileAPI/issues/40
we might see things such as `await blob.arrayBuffer()` & `await blob.text()`

[👍](https://github.com/w3c/FileAPI/issues/40#issue-159798777) it you thing it's useful

**Comment by Gozala** [comment]
@jimmywarting I understand and that’s great, but then again other libraries will still be incompatible. Right now I basically have to do that hacks to translate blobs from one library to the other - it’s not about how do I read from blob (which is from this library) but more about the fact that blobs coming from other libraries won’t work with this one & other way round so user needs to translate things back & forth. In the end it was more convenient to use forked version of this than to try and catch all edge cases when libs are incomparable due to differences

**Comment by Gozala** [comment]
Here is a very specific example why current behavior is very problematic:

`node-fetch` is common library used to polyfill `fetch` by libraries like [`cross-fetch`](https://www.npmjs.com/package/cross-fetch) that are used by other libraries like [jest-mock-fetch](https://github.com/jefflau/jest-fetch-mock) use. Which is great until you run into incompatibility issues with other popular libraries like [jsdom](https://github.com/jsdom/jsdom) caused by error deep in the stack:

```
TypeError: file argument must be a Blob
      
      at FileReaderImpl._readFile (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/file-api/FileReader-impl.js:66:13)
      at node_modules/blob-util/lib/index.js:138:14
          at new Promise (<anonymous>)
```

This error occurs because blob in one implementation doesn't interop with blob in the other library. And those issues are hard to track down because they're unrelated to the code that author has written & pretty much impossible to fix because `Blob` is concealed.
