### ISSUE TITLE
fetch().finally not apart of node-fetch.

### ISSUE THREAD

**Issue by lifeiscontent** [bitinn/node-fetch#397]
any reason why `fetch().finally` isn't included in this polyfill?

**Comment by jkantr** [comment]
`Promise#finally`, although a completed proposal and part of ES2018, is not yet including in stable node builds (since it is so new). You can get this behavior by bringing in a custom promise implementation (like `bluebird` and configuring `node-fetch` to use it for promises, ala:

``` javascript
const Bluebird = require('bluebird');
fetch.Promise = Bluebird;
```

Alternatively, `Promise#finally` will be available in node.js v10x, so you could wait until the stable release in just a few months :)
