### ISSUE TITLE
.textConverted needs to install the package encoding separately

### ISSUE THREAD

**Issue by motss** [bitinn/node-fetch#412]
Why the package `encoding` is not part of `node-fetch`'s dependencies to use `.textConverted`?

**Comment by TimothyGu** [comment]
It's intentional: we don't force people who don't use `textConverted` to install `encoding`. We should document this however.

**Comment by motss** [comment]
Ya. A line or two stating this can be helpful! 👍

**Comment by TimothyGu** [comment]
@motss Would you be interested in creating a pull request? ☺️

**Comment by motss** [comment]
@TimothyGu Sure thing. Will work on that probably on the weekend.

**Comment by peterbakonyi05** [comment]
Please note that since `encoding` is not part of the dependencies by default, when using this package with `webpack`, without installing `encoding`, webpack will fail with the usual error message: 
```
WARNING in ./node_modules/cross-fetch/node_modules/node-fetch/lib/index.es.js
Module not found: Error: Can't resolve 'encoding' in 'C:\git\halo.site\node_modules\cross-fetc
h\node_modules\node-fetch\
```

I think it would be nice to also add this to the `README`:
When using `node-fetch` with `webpack`. You either need to install `encoding` or add [ContextReplacementPlugin](https://webpack.js.org/plugins/context-replacement-plugin/)
```js
new webpack.ContextReplacementPlugin(
    /encoding$/,
    path.join(__dirname, "src"),  // location of your src
    {}
),
```

**Comment by itonics-tbeauvais** [comment]
Somehow, using the `nodeExternals()` for the `externals` option in webpack found here https://www.npmjs.com/package/webpack-node-externals

**Comment by motss** [comment]
I thought this had been fixed by one of the PRs. I can update the doc real quick with the findings from @peterbakonyi05 as well.

**Comment by motss** [comment]
I've added briefly in the doc. Please help review #511. Thank you.

**Comment by bitinn** [comment]
I have added guideline to readme and link to this issue.
