### ISSUE TITLE
Question: Should Request body really be a `Readable` stream?

### ISSUE THREAD

**Issue by CodeMan99** [bitinn/node-fetch#418]
For example, if you want to pass stdin as your request body.

```javascript
var req = new fetch.Request('http://localhost:8000', {
   body: process.stdin,
   method: 'POST'
});

fetch(req).then(...);
```

In comparison to other node http(s) tools, I would expect to able to treat a request body like a `Writable` stream.

```javascript
var req = new fetch.Request('http://localhost:8000', {
   method: 'POST'
});

fetch(req).then(...);
process.stdin.pipe(req.body);
```

Just theory crafting, so apologies if this is absurd.

**Comment by TimothyGu** [comment]
Even if it doesn't make sense, we are not in a position where we can fix this due to the fact that `body` is a ReadableStream in browsers as well. You probably want to use a [`stream.PassThrough`](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) to pass into the `Request` constructor that you can then manipulate.

**Comment by CodeMan99** [comment]
@TimothyGu Would you mind linking me to the documentation for the browser? I tried to look for that information before creating this issue and was unable to locate anything about streaming in the browser.

**Comment by CodeMan99** [comment]
I found the [whatwg spec](https://fetch.spec.whatwg.org/#concept-body).
