### ISSUE TITLE
Set connect and operation timeout separately?

### ISSUE THREAD

**Issue by laurent22** [bitinn/node-fetch#446]
I see that after a while, the lib will abort an operation after a set time - https://github.com/bitinn/node-fetch/blob/4068bed356396518e7e9c5cc2b8ccd4c137c2749/src/index.js#L58 However this is an issue when uploading large files as I want the operation to complete no matter how long it takes, so no timeout. On the other hand, if the server is unreachable and cannot be connected to, I want to abort after a set time.

So I'm wondering is there any way to set these two timeouts separately? Basically one for connection timeout and the other for operation timeout (a bit like curl)?

**Comment by bitinn** [comment]
Since Fetch spec doesn’t have such a setting, I doubt we will make the timeout option more complex.

I get your point though, in future we might expose underlying http in some way so you can customize it further. But uploading a very large file in one go will always be a tricky thing over the internet.

If others have some good suggestion feel free to chime in. I am not sure if http.Agent offers some workaround for this issue.

(From my phone)

**Comment by gajus** [comment]
You can just set timeout to `Infinity`.

**Comment by jimmywarting** [comment]
Closing this since `AbortController` will be able to solve this problem and the fack that timeout is not an spec standard
