### ISSUE TITLE
Support "redirect" attribute of Request

### ISSUE THREAD

**Issue by cpetrov** [bitinn/node-fetch#46]
See https://fetch.spec.whatwg.org/#dom-request-redirect.

The *manual* `RequestRedirect` will allow preventing HTTP 3xx responses from being automatically followed.

**Comment by bitinn** [comment]
This has been raised before #6 #23, but I don't think `manual` is exposed, ie. you can't actually stop fetch from following redirect due to https://fetch.spec.whatwg.org/#atomic-http-redirect-handling

So the `manual` description is likely for browser vendors (internal), not users (API). Also see https://github.com/github/fetch/issues/137

**Comment by cpetrov** [comment]
Thank you for the information! Closing the issue.
