### ISSUE TITLE
Proper support of HTTPS for Node 8.6.0 ~ 10.0.0

### ISSUE THREAD

**Issue by FredyC** [bitinn/node-fetch#461]
There was a breaking change back in 8.6.0 which for some reason took a long time to fix and it will land in Node 10, not sooner. Unfortunately, we are stuck with current LTS which is in 8.x line.

There is a detailed discussion here: https://github.com/nodejs/node/issues/16196#issuecomment-336647658 and the relevant PR, that is going to land in 10.x

---
# Quick workaround (otherwise continue reading)

I made my own fork of `node-fetch` which adds `ecdhCurve:auto` which is enough to have a valid cross-platform solution and it's done same way in NodeJS 10+. 

https://www.npmjs.com/package/node-fetch-auto-curve

If you are using `node-fetch` directly, just go ahead and use the fork directly. Otherwise, if you have a 3rd party dependency that is using `node-fetch`, you can win the fight with Yarn great feature called [selective dependency resolution](https://yarnpkg.com/en/docs/selective-version-resolutions). All you need to do is add this to your `package.json` and you run `yarn install`.

```
  "resolutions": {
    "node-fetch": "fredyc/node-fetch#auto-curve"
  },
```

Sadly, I cannot give you any useful advice if NPM is your choice.

**Comment by bitinn** [comment]
@FredyC 

So after reading your reply on https://github.com/prismagraphql/graphql-request/issues/84 and thinking more about it, my current understanding is:

- Your issue has more to do with `webpack` + server-side bundling, which make using `https`, a native module, tricky.
- But I do know native module can be mocked with `webpack`, it's probably not convenient, but should be doable.

So, I suggest we tackle the real problem: `webpack` bundling that prevents you from using `https.Agent`, than to mitigate it from `node-fetch` (so that you don't have to use `https.Agent`).

From my point of view:

- `node-fetch` is designed to be a nodejs package (see readme on isomorphic usage), so it assumes nodejs native API are available to users.
- `node-fetch` has been delegating many other TLS related options to `http.Agents`, it includes: self-signed certificate, corporate proxy, tcp keep alive. So `ecdhCurve` to me, is just one of those parameters.
- `node-fetch` tries not to work against nodejs default value, for example, by Fetch spec we should have kept header names' original casing, but nodejs actively lowercase them, which can cause some issues with legacy servers. We didn't try to workaround it.

All in all, it's true that nodejs' recent change on `ecdhCurve` default value have caused problems, but we know the workaround is to pass a custom `ecdhCurve` value you like, not `node-fetch` trying to set a default that some felt should be the correct setting.

I apologize for rambling, but this is my current take on this topic.

I have also asked webpack team to create more document on server-side bunlding:

- https://twitter.com/bitinn/status/1001693558510903297
- https://twitter.com/bitinn/status/1001696336088051712

**Comment by FredyC** [comment]
Honestly, I am not sure what to take from all of this. If I understand correctly, you are still against solving it on `node-fetch`? In that case, let me summarize what it means for a user who need to support current LTS.

 * User gets cryptic error like `Error: 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:772`
 * If he doesn't freak out and actually google, he might find the [NodeJS relevant issue.](https://github.com/nodejs/node/issues/16196#issuecomment-336647658)
 * Reading through all that highly technical stuff and perhaps finding there a link to this issue
 * Create `https.Agent` and pass it to `node-fetch` with `ecdhCurve:auto`
 * Fail when Webpack (or any other bundler) starts to complain that `https` is not known
 * Feel miserable

Instead all of this you could include single **harmless** property and won't influence anything, but help people having this issue. I really don't understand your stance on this.

You know, `fetch` in general is supposed to be about ease of use, so people don't need to bother with complexities of `http.Request` or `XHR` and just do `fetch(url)`. Instead, everyone who wants to support current NodeJS LTS will have to put up a quite big effort to finding information and then mitigating the problem.

Well, I am feeling like am repeating myself, so if you are still unconvinced, then I give and once I create my fork I will link it here.

**Comment by bitinn** [comment]
I understand your frustration, I really do, but it doesn't translate to a good argument.

> If I understand correctly, you are still against solving it on node-fetch side?

Yes, I am against adding that property, when `https.Agent` [is available](https://nodejs.org/api/https.html#https_class_https_agent), and when `DEFAULT_ECDH_CURVE` [is available](https://nodejs.org/api/tls.html#tls_tls_default_ecdh_curve).

- If you got dependency that doesn't expose Agent, use `DEFAULT_ECDH_CURVE` approach.
- If you got direct access to node-fetch API, use `https.Agent` approach.

Now to clarify my stand:

- It's not our job to shield everyone from Node's decision to set a default `ecdhCurve`, and [then walk it back and not backport this fix](https://github.com/nodejs/node/commit/af78840b194528a147e4683aed27a320f9764ea5).
- It's not our job to shield everyone from learning how to use webpack for server-side bundling.
- It's not our job to shield everyone from googling and feeling miserable.

You claim this property doesn't do any harm. But here is my question:

- Then why doesn't Node team backport `ecdhCurve: auto` to Node 8 LTS?

I don't know, and I welcome some answers.

**Comment by FredyC** [comment]
I am not saying that you should _shield_ someone from NodeJS team decision, but _you can_ do that very easily in this case. It's really just one property compared to the major hassle I have described above. I certainly would be more understanding if it would require doing some major breaking change to the lib, but one property ... really?

I don't know either why they did not backport it and I am kinda done arguing about that. I've updated the first post with my workaround. I am sorry if you don't like it, but this is just ridiculous. I cannot really say I understand your reasoning here.
