### ISSUE TITLE
Can not set Accept-Encoding to gzip only

### ISSUE THREAD

**Issue by eongoo** [bitinn/node-fetch#465]
In my case , I need to set Accept-Encoding to gzip only, without deflate, it seems not work, when I add 'Accept-Encoding: gzip' to headers with method POST.
p.s. compress the body manually before fetching

**Comment by bitinn** [comment]
When compress is true request object will overwrite accept-encoding, which is probably a bad idea, should preserve original encoding value if already set by users.

PR welcomed.

https://github.com/bitinn/node-fetch/blob/8aac53679d04ade28068bdec63488e35908717dd/src/request.js#L190-L193

**Comment by bitinn** [comment]
@TimothyGu but we did claim we don't have forbidden headers :)

https://github.com/bitinn/node-fetch/blob/master/LIMITS.md

I think most people are just trying to workaround issues with legacy servers, would be great for @eongoo to tell us the exact error he is facing, maybe it's fixable in other ways.

Do you happen to know any specific issues with setting custom `Accept-Encoding` header?

**Comment by TimothyGu** [comment]
> Do you happen to know any specific issues with setting custom `Accept-Encoding` header?

Not particularly, but there could be an asymmetry if the user specified `compress: true` but also their own `Accept-Encoding` header: we would be decompressing the response to a request whose requested encoding we don't control. That's why I don't feel comfortable allowing custom `Accept-Encoding` if `compress` is true.

However, we can't _only_ allow that header if `compress` is false either, because there would be only two ways of doing so:

1. Ignoring `Accept-Encoding` if `compress: true` but using `Accept-Encoding` if `compress: false`. This sounds like a footgun when people change a seemingly innocuous option.
2. Throwing an error when `Accept-Encoding` is specified but `compress` is true. This would make us deviate from browsers.

**Comment by bitinn** [comment]
In [2.2.1](https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md#v221) release I decide to make `Accept-Encoding` take precedent over `compress`, but only in Headers. So the request header will be exactly the string you set, but node-fetch will only unzip or inflate when `compress` is true.
