### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined (Response.body is undefined)

### ISSUE THREAD

**Issue by adam-nielsen** [bitinn/node-fetch#479]
I'm getting the following error:
```
TypeError: Cannot read property 'on' of undefined
    at node_modules/node-fetch/lib/body.js:122:13
    at new Promise (<anonymous>)
```
The code triggering the error is this:
```
const response = await fetch(req);
if (response.status !== 200) {
	let bodyText = await response.text();  // this line triggers the error
```
It looks like the problem comes from the fact that I am using [fetch-mock](https://github.com/wheresrhys/fetch-mock) for my tests, and I am mocking a call like this:
```
fetchMock.get(/.*$/, (url, opts) => {
	console.error('Returning 404 for unhandled mock request:', url);
	return 404;
});
```
This returned 404 code constructs a `Response` object with no `.body` (it is `undefined`) which is where the exception is coming from.

I am not sure whether this is a problem with `node-fetch` not handling a null/undefined `Response.body` or whether it's the fault of [fetch-mock](https://github.com/wheresrhys/fetch-mock) for not correctly constructing the `Response` object, however the Fetch specification seems to indicate that `.body` can be `null`, so if I'm reading that properly then it seems that `node-fetch` should be able to cope when the body is null or undefined.

**Comment by TimothyGu** [comment]
We do handle the case where `body` is `null`

https://github.com/bitinn/node-fetch/blob/287bc3bdcf75c160b1ddf645009b9c9165d920a7/src/body.js#L190-L192

but in your case `body` is `undefined`, which would never happen for an actual `Response` object. Even `new Response(undefined, ...)` will (or at least should) result in a `body` of `null`:

https://github.com/bitinn/node-fetch/blob/287bc3bdcf75c160b1ddf645009b9c9165d920a7/src/body.js#L32-L34

It would seem to me that this is not an issue in node-fetch, but I'm happy to be shown otherwise.
