### ISSUE TITLE
Unsupported browser

### ISSUE THREAD

**Issue by GConejos** [bitinn/node-fetch#526]
When I make the request for a url, there are times when I return the information correctly and other times I return the page that indicates that the browser is not compatible. For the same url, either of the two cases can happen to me.

**Comment by jimmywarting** [comment]
- Tried looking at the network request in the developer tool? 
- What those the console tell you?
- What dose your code look like?

**Comment by GConejos** [comment]
Thank you for your response. I have added the 'User-Agent' to headers and now the problem is resolved.

We are trying to parse a response from TripAdvisor and somethimes we get a search result and sometimes we get a response with an empty search result. Does anyone know from experience whether TripAdvisor is detecting that the request is coming from node-fetch and is limiting the service?

`
    let url = 'https://www.tripadvisor.es/Search?q=pedro&geo=187427';

    fetch(url, {
            method: 'GET',
            headers:  {
                'User-Agent': 'Mozilla/5.0'
            }
        })
        .then((res) => res.text())
        .then((html) => {

            //Get only the body of html
            var body = html.substring(html.indexOf("<body"), html.indexOf("</body>") + 7);

            //Remove all scripts from the body
            var script;
            do {
                script = body.substring(body.indexOf("<script"), body.indexOf("</script>") + 9);
                body = body.replace(script, '');
            }
            while (body.indexOf("<script") > 0);
            //JQuery
            return new Promise((res, rej) => {
                let $ = cheerio.load(body);
                res($)
            });

        })
        .then(($) => {
`

**Comment by jimmywarting** [comment]
They maybe do some rate limit based on IP adress or User Agent or maybe a combination of both

Try and see if there is any [x-rate-limit](https://stackoverflow.com/questions/16022624/examples-of-http-api-rate-limiting-http-response-headers) headers

You could maybe try go around the problem by using a dynamic user-agent that changes every time.

either way your problem seems to be resolved. So I'm closing this now and it don't really have anything to do about node-fetch
