### ISSUE TITLE
Setting follow to 0 does not prevent redirects

### ISSUE THREAD

**Issue by sheepsteak** [bitinn/node-fetch#6]
Passing 0 in options for 'follow' gets [turned into 20](https://github.com/bitinn/node-fetch/blob/master/index.js#L73) as 0 is "falsy".

If I change this line to allow 0 then a [maximum redirect error is thrown handling the response](https://github.com/bitinn/node-fetch/blob/master/index.js#L123).

**Comment by bitinn** [comment]
my doc might be misleading, 0 to *disable redirect limit*, not *disable following redirect*

you can use 1 to achieve what you desire, if i understand correctly.

**Comment by sonewman** [comment]
zero would never ever be set because `options.follow = opts.follow || 20;` would result in the follow being set to 20 as zero would be false. If this were set to one it would allow one redirect, rather than only allowing one request.

**Comment by bitinn** [comment]
ah i confused myself, should be fixed in next release.

**Comment by bitinn** [comment]
npm 1.0.5 should fix this issue.

**Comment by sonewman** [comment]
:+1: Awesome!

**Comment by sonewman** [comment]
This would always be an error though right? I mean if I wanted to access the headers from the redirect would that be possible? because it looks like it would only ever return an `Error` instance I notice in the spec there is a reference to a "*manual redirect flag*" https://fetch.spec.whatwg.org/#concept-request-manual-redirect-flag which looks like it would suffice for this situation.

**Comment by bitinn** [comment]
@sonewman i don't think peeking into redirect header is possible at the moment (definitely not on client side), multiple reasons, first being security.
