### ISSUE TITLE
Maybe add new read methods to blob.js?

### ISSUE THREAD

**Issue by jimmywarting** [bitinn/node-fetch#604]
w3c/FileAPI and chrome are making blob.arrayBuffer() blob.text() and blob.stream() happen

https://chromestatus.com/feature/6206980857266176
https://pr-preview.s3.amazonaws.com/w3c/FileAPI/117/795750f...42f8a45.html
[w3c/FileAPI#117](https://bit.ly/2U7Vpfl)

should we implement them too, now? or should we hold off for a while?

**Comment by bitinn** [comment]
Interesting, I see this is desirable on client-side for many reasons, which I think will eventually make it an isomorphic feature request on server-side.

If we are going to update Blob to match browser APIs, wouldn't we want to expose it too? That's the question I am thinking about: should it be a separate dependency or a part of node-fetch?

**Comment by jimmywarting** [comment]
> should it be a separate dependency or a part of node-fetch?

Not sure, i remember i tried to accomplish that with Header before (turning that into a separate module) didn't go so well for me.  ¯\_(ツ)_/¯ 

I added text and arrayBuffer to the Blob class and added test for those two.

now the question is what `stream()` should be a whatwg stream or a node stream?

**Comment by bitinn** [comment]
> Not sure, i remember i tried to accomplish that with Header before (turning that into a separate module) didn't go so well for me.

Well, I think `Headers` are much harder to do, as it's a core part of Fetch API.

I imagine `Blob` can be handled like `form-data` or `AbortController`? I think eventually, this is the right way to go, as we are going to see competing `Blob` implementations.

> now the question is what stream() should be a whatwg stream or a node stream?

The right thing to do would be WHATWG stream, the popular thing to do would be Node stream. I would go with node stream just because it's easier for nodejs users.

The good thing about removing this `Blob` dependency is: we don't have to make this decision for users, if you don't like our suggested implementation of `Blob`, use your own, as long as it sticks to a certain API.

What do you think?

(Again, I haven't looked into how Blob works nowadays, I might be totally wrong)

**Comment by bitinn** [comment]
Also it appears `Blob` isn't getting any love until your recent commits.

https://github.com/bitinn/node-fetch/commits/master/src/blob.js

It was introduced as an experimental API, I think this approach is up for a reexamination?

https://github.com/bitinn/node-fetch/blob/master/CHANGELOG.md#general-changes

**Comment by bitinn** [comment]
ping @Gozala: see if you got time to write a PR for this, so that you can use jsdom blob or our blob or whichever blob you fancy.

(I am not promising to merge it, but I think there is a good chance we might move towards that.)

(And your whole stack will need to support it before you get to use it in your application; so see if your goal is worth the price here.)

**Comment by jimmywarting** [comment]
Think header is as loose as abortControler... Request, fetch, axois, superagent could all benefit of using it

When we make a request or a response we need to be able to read the blob or file with stream() and it could be one or the other. So when we pipe whatwg stream we have to convert it

**Comment by bitinn** [comment]
> Think header is as loose as abortControler

I don't think I share this perspective:

- Just looking at how `Headers` are actually used throughout the current codebase, compared to `Blob`, `AbortSignal`, `FormData`, it's much more integrated.
- I don't think people using Request, Axios etc. are looking for a third-party implementation of a core feature. (Some may argue they have better others than Fetch, like `request.defaults`).
- We did expose `Headers` per spec, so people are free to use it.

Conceptually they might be separate, in actual use, I see few value to fully modularize it.

> So when we pipe whatwg stream we have to convert it

Internally they are buffers, I would say when given a `Blob`, we can cheat and just read from `arrayBuffer()` instead of `stream()`. There is no benefit to read from `stream()` as everything is already in memory.

So I think the `Blob.stream()` decision wouldn't directly affect us.

**Comment by jimmywarting** [comment]
> we can cheat and just read from arrayBuffer() instead of stream(). There is no benefit to read from stream() as everything is already in memory.

Yep, until someone starts to wrap a large local file with an actual fs.stream and manage to create a blob that dosen't really keep everything in memory.
But we can use that to quickly get something out and working

**Comment by bitinn** [comment]
> create a blob that dosen't really keep everything in memory.

But I think `Blob` is by definition buffers in memory? The user should be using stream directly instead of creating `Blob` then convert it to stream. Anyway, I digress.

https://w3c.github.io/FileAPI/#blob-get-stream

**Comment by jimmywarting** [comment]
<img src="https://i.stack.imgur.com/cNAud.png"> 

this is a chromes presentations of some google docs.

**Comment by bitinn** [comment]
> if you would merge two 4gb blobs to get one 8gb file the browser tab would hang

OK Maybe things have changed.

The last time I checked browsers do have quite broken stream support, and could simply OOM if you fetch a very large file (due to lack of proper back pressure).

**Comment by Gozala** [comment]
> ping @Gozala: see if you got time to write a PR for this, so that you can use jsdom blob or our blob or whichever blob you fancy.
> 

Can you please elaborate a bit on what you mean & how this relates to this issue ?
What this issue proposes: `blob.arrayBuffer()`, `blob.text()`, and `blob.stream()` will not help with JSDOM or any other library interop because primary issue is that `blob instanceof Blob` is false when `Blob` instance and constructor are from different libraries & that is also how both JSDOM and this library check if provided argument is `Blob`.

> (I am not promising to merge it, but I think there is a good chance we might move towards that.)
> 
> (And your whole stack will need to support it before you get to use it in your application; so see if your goal is worth the price here.)

Maybe you're suggesting to update both this library and JSDOM to add those methods so neither would need to do `blob instanceof Blob`. In which case I can see it working, however I'm not convinced that is the best strategy to resolve this issue. IMO best strategy would be to factor out conflicting `Blob` implementations across libraries into separate one and share it as common dependency across them. With that approach:
1. Adding additional read methods are not strictly necessary.
2. Improvements like new read methods could be cooperated on.

@bitinn If you meant something else please elaborate.

**Comment by jimmywarting** [comment]
> because primary issue is that blob instanceof Blob is false when Blob instance and constructor are from different libraries. That is also how both JSDOM and this library check if provided argument is Blob.

Going forward I think we will remove the instance of check and and do type check to see if it looks like a blob and has the new reading methods. So any blob-like object can be passed into node-fetch...

**Comment by Gozala** [comment]
Would you mind providing more details what exactly do you have in mind ? Specifically it’s unclear to me how that would resolve issue with JSDOM doing `blob instanceof Blob` where `blob` came for `response.blob()`

**Comment by jimmywarting** [comment]
It doesn't solve jsdom but it would allow us to utilize jsdom blobs in node-fetch if it has new read methods
but jsdom have decided to be more strict and use instance of checks and they will probably use there own blob class that are tight with there's file reader. So maybe you might not want to use fileReader? Or you can monkey patch the readAs method to read the file using the blobs methods

**Comment by Gozala** [comment]
@jimmywarting I think you're misunderstanding my issue. I'm not having issue with reading data from blobs that come from `node-fetch`, nor I have issue with `JSDOM` itself. Issue I'm having is that project I'm working with uses `jest` that uses`JSDOM` + `mock-js-fetch` and bunch of other libraries that do not interop.

Project I'm personally interested in is targeted at browsers that have all of those APIs natively, it's just trying to get it tested in node is really, really painful because dependencies 3 levels deep have disagreements on what `Blob` polyfill to use. So issues I'm having really has nothing to do with reading blobs it's more like when I use `fetch(...)` and pass returned `Response` to some dependency it will do `response.blob()` and pass it further down some other dependency that fails to recognize it's blob and turns it into `[object Object]` and same is true other way round.

Only way these issues could be resolved if all these libraries decide to interop which could be through `.arrayBuffer()` method or by sharing `Blob` polyfill. But then again, unless there is a will to inetrop no specific methods will help.

Now that being said even though node-fetch recognizing `.arrayBuffer()` method would help resolve issues issue of passing third-party blobs to `Response` by patching `DOMJS.Blob.prototype.arrayBuffer = ...` it would be far more helpful if `node-fetch` allowed providing `Blob` class as that would then allow user to do e.g. `global.Blob = DOMJS.Blob` and get interop both ways.

**Comment by bitinn** [comment]
> Only way these issues could be resolved if all these libraries decide to interop which could be through .arrayBuffer() method or by sharing Blob polyfill. But then again, unless there is a will to inetrop no specific methods will help.

What we are saying is:

- We plan to remove our `Blob` polyfill and likely make it a separate package.
- We plan to check for `Blob` API instead of `instanceof Blob` so that others can provide us a different `Blob` polyfill if they wish.

> IMO best strategy would be to factor out conflicting Blob implementations across libraries into own library that everyone can depend upon. With that approach:

But if you want all modules to suddenly adopt this approach, that's a lot of work, especially jsdom which has strict spec requirement. Which is why I mentioned you should consider if it's worth your time.

**Comment by Gozala** [comment]
> What we are saying is:
> 
>    * We plan to remove our `Blob` polyfill and likely make it a separate package.
> 

This sounds great, I'd be happy to help with this effort!

>    * We plan to check for `Blob` API instead of `instanceof Blob` so that others can provide us a different `Blob` polyfill if they wish.

Do you have a specific idea how that check should occur ? Asking because there are two separate issues:

1. `node-fetch` does not recognize blobs passed to it `new Response(new OtherLib.Blob(...))` which can be addressed e.g. via `typeof blob.arrayBuffer === "function"`.
2. `node-fetch` returning own blob implementation `(await new Response('hello').blob()) instanceof OtherLib.Blob` 

I personally would propose a way to address both in `node-fetch` by something like `const Blob = global.Blob || require('node-blob').Blob`

I'd be happy to help with this effort as well.

 
> But if you want all modules to suddenly adopt this approach, that's a lot of work, especially jsdom which has strict spec requirement. Which is why I mentioned you should consider if it's worth your time.

I understand that. However If there is a way to bring own `Blob` implementation say via `global.Blob` incompatibility with JSDOM can be addressed simply by setting `global.Blob = JSDOM.Blob`, which is not ideal but far better than what we have today.

It is also worth mentioning that I have being running into this problem in other contexts like https://github.com/RangerMauve/webrun/ as well which would be addressed without even having to resort to these hacks.

**Comment by jimmywarting** [comment]
>1. node-fetch does not recognize blobs passed to it new Response(new OtherLib.Blob(...)) which can be addressed e.g. via typeof blob.arrayBuffer === "function".

That is probably what we are going to do eventually, perhaps some more type checking to see if it matches a blob and not some random object like `obj = {arrayBuffer() {}}`

> 2. node-fetch returning own blob implementation (await new Response('hello').blob()) instanceof OtherLib.Blob
> 
> I personally would propose a way to address both in node-fetch by something like const Blob = global.Blob || require('node-blob').Blob

Suggest that we do simulera things to what we did with promise.

```js
fetch.promise = bluebird
fetch.blob = CustomBlob
```
