### ISSUE TITLE
HEAD/OPTIONS not supported

### ISSUE THREAD

**Issue by niftylettuce** [bitinn/node-fetch#61]
I think we need to patch <https://github.com/bitinn/node-fetch/blob/fd3f89fcd94e5bcee31de4cbca4c15cd79999b07/index.js#L85-L93> to account for HEAD method that has a zero length body.

**Comment by niftylettuce** [comment]
`SyntaxError: Unexpected end of input`

**Comment by bitinn** [comment]
HEAD is supported, see this test case: https://github.com/bitinn/node-fetch/blob/master/test/test.js#L593-L604

I haven't tested OPTIONS, I assume it would work (given it's handled by `http.request`).

**Comment by niftylettuce** [comment]
@bitinn is it possible for you to look into why these two methods aren't working on Frisbee? <https://github.com/niftylettuce/frisbee/blob/master/test/unit/node.test.js#L137>

**Comment by bitinn** [comment]
Hard to tell without looking at how you setup the test parameters. If you have got a simplified test case it might be easier to figure out (to be honest, you might figure out why if you do write a test case specifically for OPTIONS)

**Comment by bitinn** [comment]
release v1.4.0 have added explicit tests for OPTIONS support.

note that:

- HEAD request won't give you the response body, hence the error `SyntaxError: Unexpected end of input`, likely thrown when trying to parse an empty body as json.
- Node v0.10 `Allow` header support is buggy, if you only see the first value for your `Allow` header, use a string instead of array (referring to server-side response header)

**Comment by milahu** [comment]
> HEAD is supported

for the record:

```js
// bash: curl -I https://httpbin.org/post
const response = await fetch('https://httpbin.org/', { method: 'HEAD' });
const contentType = response.headers.get('content-type');
```

https://github.com/node-fetch/node-fetch#accessing-headers-and-other-meta-data
