### ISSUE TITLE
401 response code is shown as 200

### ISSUE THREAD

**Issue by 1999** [bitinn/node-fetch#663]
```
var nodeFetch = require("node-fetch")
nodeFetch('https://bitbucket.org/atlassian/foo/get/master.zip').then((res) => {
  console.log(res.status);
});
```

This URL returns 401 but for some reason, I get back 200.

**Comment by gr2m** [comment]
Could confirm in shell

```shell
$ curl -i https://bitbucket.org/atlassian/foo/get/master.zip
HTTP/2 401 
```

Here is the above code on runkit, logging `200`

https://runkit.com/gr2m/5d563f0191db88001372f38a

**Comment by 1999** [comment]
Thanks, that's exactly what I'm talking about.

**Comment by norcal82** [comment]
Curl won't follow redirects with the `-i` flag. Curls `-L` flag should tell it to follow the redirects. 

Fetch defaults to follow redirects. try passing `{redirect: 'manual}`

``` js
var nodeFetch = require("node-fetch")
nodeFetch('https://bitbucket.org/atlassian/foo/get/master.zip', {redirect: 'manual'}).then((res) => {
  console.log(res.status);
});

=> 302
```

**Comment by 1999** [comment]
There's something wrong about this URL for me. Simple `curl` without any flags just returns a 401 but `node-fetch` as you said @norcal82 returns 302. How come?

**Comment by norcal82** [comment]
@1999 that zip url requires authentication. So when you try to access it without any auth info it will redirect you to a login page. The login page is returning the successful `200`. Curl wont follow redirects with just the `curl` command. The  `-L`  flag should make curl follow the redirect and return a `200`. `3xx` codes indicate a redirection. fetch defaults to follow the redirects which is why without that param it is returning a `200`.

**Comment by bitinn** [comment]
I will be closing this as it seems like a misunderstanding of server behavior.
