### ISSUE TITLE
Error: incorrect header check

### ISSUE THREAD

**Issue by maticrivo** [bitinn/node-fetch#93]
I'm using node-fetch to fetch a URL that returns a JSON and I'm getting an error when parsing the response with `response.json()`.
The error I'm getting is: `Error: incorrect header check`
i curled the URL and there are no redirects or anything, this is the response header from curl:
```
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 57338
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
X-AspNetMvc-Version: 5.2
X-AspNet-Version: 4.0.30319
Set-Cookie: WebApplication.Context=Culture=he-IL&UICulture=he-IL&AddressId=0&SearchCityId=0&SearchStreetId=0&SearchStreetAddress=&SearchStreetName=&SearchCityName=&SearchHouseNumber=&SearchCountryCode=&SearchFullAddress=&ShoppingCartGuid=00000000-0000-0000-0000-000000000000&WebsiteId=10bis&DomainId=10bis&BrowsingRestaurantId=0&SearchPhrase=&NavigationStartPoint=&HideAllPoups=False&IsKosher=False&DesiredDateAndTime=01/01/0001 00:00:00&CouponCode=&CompanyPreferredSite=&CompanyAdminPermissionLevel=&PreferredResList=List&PreferredResListSitting=Map; expires=Thu, 24-Mar-2016 13:11:08 GMT; path=/
X-Powered-By: ASP.NET
Date: Thu, 24 Mar 2016 09:11:08 GMT
```

using latest node-fetch version `node-fetch@1.4.1`

any idea how to fix this?

**Comment by bitinn** [comment]
This error is coming from node.js zlib, similar to #45 (also a IIS server, if I recalled correctly)

But it has nothing to with http headers, instead, it's complaining about the header of response body (which would be in `gzip` or `deflate` compression in order to trigger this error).

If you must handle this page, option `compress: false` should cause server to send back a non-compressed version, which `node-fetch` should be able to read.

Note that `curl` might not send content-encoding header by default, so to properly test if that server is returning valid gzip/deflate. See this:

http://stackoverflow.com/questions/9140178/how-can-i-tell-if-my-server-is-serving-gzipped-content

**Comment by bitinn** [comment]
closing as issue is from lower level

though with v1.5.0 you might be able to handle this error more gracefully (still, you need to correct the response to be able to extract with built-in zlib)

**Comment by ankit-1729** [comment]
I just passed the `options` object to the fetch call and it worked.
const options = {
compress : false
} 

Thanks a lot @bitinn . You came like a messiah.
